[package]
name = "kana2phone"
version = "0.1.0"
authors = ["corocn <crsk.plmzh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8.0", features = ["macros"] }
regex = "1.4.5"
